name: Lint
on:
  push:
    branches:
      - master
    paths:
      - '!docs/**'
  pull_request:
    paths:
      - '**'
      - '!docs/**'
env:
  FORCE_COLOR: 1
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint
        uses: kairos-io/kairos-linter@main
        with:
          yaml: true
          yaml-dirs: ".github/workflows/ overlay/"
          go: true
          hadolint: true
          hadolint-dir: images
