name: Cloud Config Schema
on:
  push:
    branches:
      - schematest
  # tags:
  #   - v*
jobs:
  generate-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: schematest
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Generate cloud-config Schema
        run: |
          ./earthly.sh +generate-schema
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          base: schematest
          commit-message: ":book: Update Schema"
          title: ":book: Update Schema"
          body: "Update latest cloud config schema release"
          signoff: true
